services:
  - type: web
    name: portal-ics-logistik
    env: node
    plan: starter
    buildCommand: npm install --include=dev && npm run build --workspace @ics/template-web
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TEMPLATE_DESIGNER_URL
        sync: false
